title: cjRepo
url: https://cj81499.github.io
baseurl: "/repo"
description: cj81499's Cydia Repo
permalink: pretty
exclude:
  - README.md
collections:
  packages:
    output: true
    permalink: depictions/:path/
  changelogs:
    output: true
    permalink: depictions/:path/changelog/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      type: packages
    values:
      layout: package
      noheader: true
  - scope:
      type: changelogs
    values:
      layout: changelog
      noheader: true
sass:
  style: compressed
